project/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/store/urls.py
from django.urls import path
from .views import IndexView, product_detail, CategoryView

app_name = 'store'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>', product_detail, name='product_detail'),
    path('category/<int:pk>/', CategoryView.as_view(), name='category_detail'),
]

project/store/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название категории')
    slug = models.SlugField(max_length=200, unique=True)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True,
                               blank=True, verbose_name='Родительская категория')

    class Meta:
        ordering = ['name', ]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolut_url(self):
        return reverse('store:category_detail', kwargs={'pk': self.pk})


class Brand(models.Model):
    name = models.CharField(max_length=100, verbose_name='Бренд')
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ['name', ]
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'

    def __str__(self):
        return self.name


def image_forlder(instance, filename):
    filename = f"{instance.slug}.{filename.split('.')[1]}"
    return f'images/products/{instance.slug}/{filename}'


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='products', blank=True)
    model = models.CharField(max_length=100, verbose_name='Модель')
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Стоимость')
    image = models.ImageField(null=True, blank=True, upload_to=image_forlder, verbose_name='Изображение')
    stock = models.PositiveIntegerField(verbose_name='Остатки')
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ['brand', 'model', ]
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f'{self.brand} {self.model}'

    def get_absolut_url(self):
        return reverse('store:product_detail', kwargs={'pk': self.pk})


class Article(models.Model):

    title = models.CharField(max_length=350, verbose_name='Заголовок')
    content = RichTextUploadingField(verbose_name='Контент')
    published = models.DateField(verbose_name='Дата публикации')
    products = models.ManyToManyField(Product, verbose_name='Товары')
    is_active = models.BooleanField(default=True, verbose_name='Активна')

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['is_active', '-published', 'title', ]

    def __str__(self):
        return self.title


class Feedback(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='feedbacks')
    name = models.CharField(max_length=150, verbose_name='Имя', default='Аноним')
    text = models.TextField(verbose_name='Отзыв на товар')
    rating = models.IntegerField(verbose_name='Оценка')  # для хранения информации о кол-ве присовенных звезд

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'
        ordering = ['pk', ]

project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru" >
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>Graduation Work - {% block title %}{% endblock %}</title>
  {% load bootstrap4 %}
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
  <link rel="stylesheet" href='{% static "bootstrap.min.css" %}'>
  <link rel="stylesheet" href='{% static "main.css" %}'>
</head>
<body class="" data-gr-c-s-loaded="true">

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Просто магазин</a>

      <img src="{% static 'logo.svg' %}" alt="Shop" width="90" height="90">
      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link active" href="/">
              Главная</a>
          </li>

          {% for main_category in main_categories %}
              <li class="nav-item dropdown">
                  {% if main_category.category_set.all %}
                      <a class="nav-link dropdown-toggle" href="{% url 'store:category_detail' main_category.id %}" id="dropdown01"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ main_category.name }}</a>
                  {% else %}
                      <a class="nav-link" href="{% url 'store:category_detail' main_category.id %}">{{ main_category.name }}</a>
                  {% endif %}

                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    {% for child in main_category.category_set.all %}
                        <a class="dropdown-item" href="{% url 'store:category_detail' child.id %}">{{ child.name }}</a>
                    {% endfor %}
                </div>
              </li>
          {% endfor %}
        </ul>
          {% with total_items=cart|length %}
            {% if cart|length > 0 %}
              <a class="btn btn-outline-success my-2 my-sm-0" role="button"
                 href="/cart/">Корзина: {{ cart.get_total_price }} руб.</a>
            {% else %}
              <a class="btn btn-outline-success my-2 my-sm-0" role="button"
                href="/cart/">Корзина</a>
            {% endif %}
          {% endwith %}


        {% if user.is_authenticated %}
          <a class="btn btn-outline-success my-2 my-sm-0" role="button"
             href="{% url 'logout' %}">Выйти</a>
        {% else %}
          <a class="btn btn-outline-success my-2 my-sm-0" role="button"
             href="{% url 'login' %}">Войти</a>
          <a class="btn btn-outline-success my-2 my-sm-0" role="button"
             href="{% url 'signup' %}">Зарегистрироваться</a>
        {% endif %}
      </div>
    </nav>
      {% block content %}
      {% endblock %}
    <hr>
    <footer class="container">
      <p>© Просто магазин 2018</p>
    </footer>
    <script src='{% static "jquery-3.3.1.slim.min.js" %}'></script>
    <script src='{% static "popper.min.js" %}'></script>
</body>
</html>

project/templates/home.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}Главная страница{% endblock %}

{% block content %}
<main role="main">
  {% for article in articles %}
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-4">{{ article.title }}</h1>
          <p>{{ article.content|safe }}</p>
      </div>
    </div>
    {% if article.products %}
      <div class="container mb-5">
        <div class="row">
          {% for product in article.products.all %}
            <div class="col-md-4">
              <a class="gray-dark-link" href="{{ product.get_absolut_url }}">
                <h3 class="product-title">{{ product }}</h3>
                {% thumbnail product.image 'x250' as im %}
                  <img src="{{ im.url }}" class="image-detail">
                {% endthumbnail %}
              </a>
              <p class="mt-3">Стоимость: {{ product.price }} руб.</p>
            </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}
  {% endfor %}
</main>
{% endblock %}

project/templates/signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}