project/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

project/orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/store/urls.py
from django.urls import path
from .views import IndexView, product_detail, CategoryView

app_name = 'store'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>', product_detail, name='product_detail'),
    path('category/<int:pk>/', CategoryView.as_view(), name='category_detail'),
]

project/cart/models.py
from django.db import models

# Create your models here.

project/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, f'{str(i)} шт.') for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, label='Колличество', coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

project/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:cart_detail')


def cart_detail(request):
    context = {}
    context['cart'] = Cart(request)

    return render(request, 'cart/detail.html', context)

project/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
<div class="container mt-3">
  <div class="row">
    <div class="col-lg-6 col-md-9 col-sm-12 order-md-2 mb-4">
      {% if errors %}
          {% for er in errors %}
            <div class="alert alert-primary mt-5 pt-3" role="alert">
              <h3>Ошибка</h3>
              {{ er }}
              Пожалуйста <a href="{% url 'login' %}?next=/cart/" class="alert-link">Войдите</a> или
               <a href="{% url 'signup' %}?next=/cart/" class="alert-link">Зарегистрируйтесь</a>.
            </div>
          {% endfor %}
      {% endif %}
      <h4 class="d-flex justify-content-between align-items-center mt-5 pt-3 mb-3">
        {% if cart.get_total_price %}
          <span class="text-muted">Ваша корзина</span>
          <span class="badge badge-secondary badge-pill">{{ cart.get_total_price }} руб.</span>
        {% else %}
          <span class="text-muted">Ваша корзина пуста</span>
        {% endif %}
      </h4>
      <ul class="list-group mb-3">
          {% for item in cart %}
            {% with product=item.product %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                  <div>
                    <a href="{% url 'store:product_detail' product.id %}">
                      <h6 class="my-0">{{ product }}</h6>
                    </a>
                    <small class="text-muted">{{ product.description }}</small>
                  </div>
                  <span class="text-muted"> {{ item.quantity }} </span>
                  <span class="text-muted">|</span>
                  <span class="text-muted">
                      <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
                  </span>
                </li>
            {% endwith %}
          {% endfor %}
      </ul>
      {% if cart.get_total_price %}
        <form class="card p-2" action="{% url 'orders:order_create' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary">Заказать</button>
        </form>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}