project/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/store/urls.py
from django.urls import path
from .views import IndexView, product_detail, CategoryView

app_name = 'store'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>', product_detail, name='product_detail'),
    path('category/<int:pk>/', CategoryView.as_view(), name='category_detail'),
]

project/store/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название категории')
    slug = models.SlugField(max_length=200, unique=True)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True,
                               blank=True, verbose_name='Родительская категория')

    class Meta:
        ordering = ['name', ]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolut_url(self):
        return reverse('store:category_detail', kwargs={'pk': self.pk})


class Brand(models.Model):
    name = models.CharField(max_length=100, verbose_name='Бренд')
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ['name', ]
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'

    def __str__(self):
        return self.name


def image_forlder(instance, filename):
    filename = f"{instance.slug}.{filename.split('.')[1]}"
    return f'images/products/{instance.slug}/{filename}'


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='products', blank=True)
    model = models.CharField(max_length=100, verbose_name='Модель')
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Стоимость')
    image = models.ImageField(null=True, blank=True, upload_to=image_forlder, verbose_name='Изображение')
    stock = models.PositiveIntegerField(verbose_name='Остатки')
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ['brand', 'model', ]
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f'{self.brand} {self.model}'

    def get_absolut_url(self):
        return reverse('store:product_detail', kwargs={'pk': self.pk})


class Article(models.Model):

    title = models.CharField(max_length=350, verbose_name='Заголовок')
    content = RichTextUploadingField(verbose_name='Контент')
    published = models.DateField(verbose_name='Дата публикации')
    products = models.ManyToManyField(Product, verbose_name='Товары')
    is_active = models.BooleanField(default=True, verbose_name='Активна')

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['is_active', '-published', 'title', ]

    def __str__(self):
        return self.title


class Feedback(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='feedbacks')
    name = models.CharField(max_length=150, verbose_name='Имя', default='Аноним')
    text = models.TextField(verbose_name='Отзыв на товар')
    rating = models.IntegerField(verbose_name='Оценка')  # для хранения информации о кол-ве присовенных звезд

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'
        ordering = ['pk', ]

project/store/forms.py
from django import forms
from .models import Article, Feedback
from ckeditor.widgets import CKEditorWidget


class ArticleAdminForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Article
        fields = ['published', 'title', 'content', 'products', ]


PRODUCT_RATING = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
)


class FeedbackForm(forms.ModelForm):
    name = forms.CharField(label='Имя')
    text = forms.CharField(label='Отзыв', widget=forms.widgets.Textarea())
    rating = forms.ChoiceField(label='Оценка', choices=PRODUCT_RATING, widget=forms.RadioSelect())

    class Meta:
        model = Feedback
        exclude = ['product']

project/store/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from .models import Category, Product, Article, Feedback
from .forms import FeedbackForm
from cart.forms import CartAddProductForm


class IndexView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['articles'] = Article.objects.filter(is_active=True)

        return context


def product_detail(request, pk):
    context = {}
    template_name = 'store/detail.html'
    product = get_object_or_404(Product, id=pk, available=True)
    context['product'] = product
    context['feedbacks'] = Feedback.objects.filter(product=product)
    cart_product_form = CartAddProductForm()
    context['cart_product_form'] = cart_product_form

    if request.method == 'POST':
        f = FeedbackForm(request.POST)
        new_feedback = f.save(commit=False)
        new_feedback.product = Product.objects.get(pk=pk)
        new_feedback.save()

        request.session["reviewed_products"] += [pk]
        context['is_review_exist'] = True

        return render(request, template_name, context)

    if not request.session.get('reviewed_products', False):
        request.session["reviewed_products"] = []
        context['is_review_exist'] = False
        context['form'] = FeedbackForm()
    else:
        if pk not in request.session["reviewed_products"]:
            context['is_review_exist'] = False
            context['form'] = FeedbackForm()
        else:
            context['is_review_exist'] = True

    return render(request, template_name, context)


class CategoryView(ListView):
    template_name = 'store/category.html'
    context_object_name = 'products'
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(category=self.kwargs['pk'])

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        cart_product_form = CartAddProductForm()
        context['cart_product_form'] = cart_product_form
        context['category'] = Category.objects.get(pk=self.kwargs['pk'])

        return context

project/templates/store/category.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}
    Category
{% endblock %}

{% block content %}
  <main role="main">
    <div class="container">
        <h1 class="mt-4 pt-5">{{ category.name }}</h1>
        {% if products %}
          <div class="row">
              {% for product in products %}
                <div class="col-md-4">
                  <a class="gray-dark-link" href="{% url 'store:product_detail' product.id %}">
                    <h3 class="product-title">{{ product }}</h3>
                    {% thumbnail product.image 'x250' as im %}
                      <img src="{{ im.url }}" class="image-detail">
                    {% endthumbnail %}
                  </a>
                  <p class="mt-3">Стоимость: {{ product.price }} руб.</p>
                  <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {% csrf_token %}
                    {{ cart_product_form }}
                    <input type="submit" class="btn btn-secondary" value="Добавить в корзину">
                  </form>
                </div>
              {% endfor %}
          </div>
          {% if is_paginated %}
            <div class="pagination mt-3">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
                    {% endif %}
                    <span class="page-current">
                        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                    {% endif %}
                </span>
            </div>
          {% endif %}
        {% else %}
          <h4>В этом разделе пока ничего нет! :(</h4>
        {% endif %}
    </div>
</main>
{% endblock %}

project/templates/store/detail.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
<main role="main">
  <div class="container mt-3">
    <div class="row">
      <div class="col-md-12">
        <h3 class="mt-5 pt-3">{{ product }}</h3>
        {% thumbnail product.image 'x250' as im %}
          <img src="{{ im.url }}" class="image-detail mt-3">
        {% endthumbnail %}
        <p class="pt-3">{{ product.description }}</p>
        <p class="price pt-3">Стоимость: {{ product.price }} руб.</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% csrf_token %}
            {{ cart_product_form }}
            <input type="submit" class="btn btn-secondary" value="Добавить в корзину">
        </form>
      </div>
    </div>
    <hr>
    {% for fb in feedbacks %}
        {% if fb.rating == 5 %}
            ★★★★★ <span>{{ fb.name }}</span>
        {% elif fb.rating == 4 %}
            ★★★★ <span>{{ fb.name }}</span>
        {% elif fb.rating == 3 %}
            ★★★ <span>{{ fb.name }}</span>
        {% elif fb.rating == 2 %}
            ★★ <span>{{ fb.name }}</span>
        {% elif fb.rating == 1 %}
            ★ <span>{{ fb.name }}</span>
        {% endif %}
        <p>{{ fb.text }}</p>
    {% endfor %}
    <hr>
    {% if not is_review_exist %}
      <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
          <h4>Оставьте отзыв:</h4>
            <form action="" method="POST">
              {% csrf_token %}
              <table>
                {% if form.non_field_errors %}
                  <ul>
                    {% for error in form.non_field_errors %}
                    <li><em>{{ error|escape }}</em></em></li>
                    {% endfor %}
                  </ul>
                {% endif %}
                <p>{{ form.name.label_tag }}<br>{{ form.name }}
                {{ form.name.help_text }}</p>
                <p>{{ form.text.label_tag }}<br>{{ form.text }}
                {{ form.text.help_text }}</p>
                <p>{{ form.rating.label_tag }}<br>{{ form.rating }}
                {{ form.rating.help_text }}</p>
              </table>
              <input type="submit" value="Добавить отзыв">
            </form>
      </div>
    {% endif %}
    </div>
  </div>
</main>
{% endblock %}